"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EQUINOR_GREEN = exports.EQUINOR_BLACK = exports.RED_LOGO = exports.RED = exports.GREEN_LIGHT = exports.PURPLE_LIGHT = exports.YELLOW_LIGHT = exports.YELLOW = exports.PINK_BACKGROUND = exports.PINK_LIGHT = exports.PINK = exports.GRAY_BACKGROUND = exports.GRAY_MAIN = exports.GRAY_4 = exports.GRAY_3 = exports.GRAY_2 = exports.GRAY_1 = exports.BLACK_LIGHT = exports.BLACK_GRAY = exports.BLACK = exports.BLUE_LIGHT_BACKGROUND = exports.BLUE_DARK = exports.BLUE_LIGHT = exports.BLUE = void 0;
exports.BLUE = '#0087b8';
exports.BLUE_LIGHT = '#c2e2ee';
exports.BLUE_DARK = '#40537d';
exports.BLUE_LIGHT_BACKGROUND = '#e7f4f7';
exports.BLACK = '#000000';
exports.BLACK_GRAY = '#424242';
exports.BLACK_LIGHT = '#323232';
exports.GRAY_1 = '#333333';
exports.GRAY_2 = '#808080';
exports.GRAY_3 = '#E4E4E4';
exports.GRAY_4 = '#f2f2f2';
exports.GRAY_MAIN = '#fafafa';
exports.GRAY_BACKGROUND = "#fafafa";
exports.PINK = '#FE30A1';
exports.PINK_LIGHT = '#ffcddf';
exports.PINK_BACKGROUND = '#FEECF0';
exports.YELLOW = '#fefe00';
exports.YELLOW_LIGHT = '#fff6d6';
exports.PURPLE_LIGHT = '#dbd1e2';
exports.GREEN_LIGHT = '#d2e6b4';
exports.RED = '#fe3824';
exports.RED_LOGO = '#FF1243';
exports.EQUINOR_BLACK = '#253746';
exports.EQUINOR_GREEN = '#007079';
